services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: ptnaza
      POSTGRES_PASSWORD: ptnaza
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: budget_flow
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - budget-flow
    restart: unless-stopped
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - budget-flow
    restart: unless-stopped
    depends_on:
      - postgres
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  budget-flow:
    driver: bridge
volumes:
  postgres:
    driver: local
  pgadmin: