services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: ptnaza
      POSTGRES_PASSWORD: ptnaza
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: budget_flow
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - budget-flow
    restart: unless-stopped
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - budget-flow
    restart: unless-stopped
    depends_on:
      - postgres
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  config-server:
    container_name: config-server
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - budget-flow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - budget-flow
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    container_name: gateway
    image: gateway
    ports:
      - "8000:8000"
    networks:
      - budget-flow
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
networks:
  budget-flow:
    driver: bridge
volumes:
  postgres:
    driver: local
  pgadmin: