/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatisticsByMonthRequest } from '../../models/statistics-by-month-request';
import { SumResponse } from '../../models/sum-response';

export interface GetSumOfIncomesByMonth$Params {
      body: StatisticsByMonthRequest
}

export function getSumOfIncomesByMonth(http: HttpClient, rootUrl: string, params: GetSumOfIncomesByMonth$Params, context?: HttpContext): Observable<StrictHttpResponse<SumResponse>> {
  const rb = new RequestBuilder(rootUrl, getSumOfIncomesByMonth.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SumResponse>;
    })
  );
}

getSumOfIncomesByMonth.PATH = '/expenses/income/getSumOfIncomes';
