/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseForStatistics } from '../../models/response-for-statistics';
import { StatisticsByMonthRequest } from '../../models/statistics-by-month-request';

export interface GetStatisticsByMonth1$Params {
      body: StatisticsByMonthRequest
}

export function getStatisticsByMonth1(http: HttpClient, rootUrl: string, params: GetStatisticsByMonth1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ResponseForStatistics>>> {
  const rb = new RequestBuilder(rootUrl, getStatisticsByMonth1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ResponseForStatistics>>;
    })
  );
}

getStatisticsByMonth1.PATH = '/expenses/income/statistics';
