/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryRequest } from '../../models/category-request';
import { CategoryResponse } from '../../models/category-response';

export interface GetAllCategory$Params {
  request: CategoryRequest;
}

export function getAllCategory(http: HttpClient, rootUrl: string, params: GetAllCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllCategory.PATH, 'get');
  if (params) {
    rb.query('request', params.request, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryResponse>>;
    })
  );
}

getAllCategory.PATH = '/expenses/category/getCategoriesByType';
