/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseRequest } from '../../models/expense-request';
import { ExpenseResponse } from '../../models/expense-response';

export interface AddExpense$Params {
      body: ExpenseRequest
}

export function addExpense(http: HttpClient, rootUrl: string, params: AddExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseResponse>> {
  const rb = new RequestBuilder(rootUrl, addExpense.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseResponse>;
    })
  );
}

addExpense.PATH = '/expenses';
