/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseCalendarFieldInfo } from '../../models/expense-calendar-field-info';

export interface GetExpensesToCalendarByCategory$Params {
}

export function getExpensesToCalendarByCategory(http: HttpClient, rootUrl: string, params?: GetExpensesToCalendarByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExpenseCalendarFieldInfo>>> {
  const rb = new RequestBuilder(rootUrl, getExpensesToCalendarByCategory.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExpenseCalendarFieldInfo>>;
    })
  );
}

getExpensesToCalendarByCategory.PATH = '/expenses/expensesToCalendarByCategory';
