/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseCategoryRequest } from '../models/expense-category-request';
export interface ExpenseRequest {
  amount?: number;
  expenseCategoryRequest?: ExpenseCategoryRequest;
  expenseDate?: string;
  id?: number;
  name?: string;
  note?: string;
}
