/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpenseResponseForStatistics {
  amount?: number;
  averageAmount?: number;
  name?: string;
}
