/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseCategory } from '../models/expense-category';
export interface ExpenseRequest {
  amount?: number;
  expenseCategory?: ExpenseCategory;
  expenseDate?: string;
  id?: number;
  name: string;
  note?: string;
  userId?: number;
}
