/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
export interface ExpenseResponse {

  /**
   * Kwota wydatku
   */
  amount: number;
  categoryResponse?: CategoryResponse;
  createdDate?: string;
  expenseDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  note?: string;
  userId?: number;

  [key: string]: any;
}
