/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpenseCategoryResponse {
  createdByUserId?: number;
  id?: number;
  name?: string;
}
