/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseCategory } from '../models/expense-category';
export interface ExpenseResponse {

  /**
   * Kwota wydatku
   */
  amount: number;
  createdDate?: string;
  expenseCategory?: ExpenseCategory;
  expenseDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  note?: string;
  userId?: number;
  [key: string]:any
}
