/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpenseCalendarFieldInfo {
  date?: string;
  hexColor?: string;
  name?: string;
  value?: number;
}
