/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupResponse {
  createdByUserId?: number;
  description?: string;
  id?: number;
  name?: string;
  users?: Array<number>;
}
