/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupResponseForExpenseService {
  groupId?: number;
  isInGroup?: boolean;
  users?: Array<number>;
}
