/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface GroupResponseWithUser {
  createdByUserId?: number;
  description?: string;
  id?: number;
  name?: string;
  usersData?: Array<UserResponse>;
}
