/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryRequest } from '../models/category-request';
export interface IncomeRequest {
  amount?: number;
  categoryRequest?: CategoryRequest;
  id?: number;
  incomeDate?: string;
  name?: string;
}
