/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IncomeCategory } from '../models/income-category';
export interface IncomeRequest {
  amount?: number;
  id?: number;
  incomeCategory?: IncomeCategory;
  incomeDate?: string;
  name?: string;
}
