/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeRequest {
  amount?: number;
  id?: number;
  incomeDate?: string;
  name?: string;
}
