/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
export interface IncomeResponse {
  amount?: number;
  categoryResponse?: CategoryResponse;
  id?: number;
  incomeDate?: string;
  name?: string;
  userId?: number;

  [key: string]: any;
}
