/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeResponse {
  amount?: number;
  id?: number;
  incomeDate?: string;
  name?: string;
  userId?: number;
}
