/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeCategoryResponse } from '../../models/income-category-response';

export interface GetAllIncomeCategories$Params {
}

export function getAllIncomeCategories(http: HttpClient, rootUrl: string, params?: GetAllIncomeCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllIncomeCategories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IncomeCategoryResponse>>;
    })
  );
}

getAllIncomeCategories.PATH = '/expenses/incomeCategory/getAllIncomeCategories';
